steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "PUBLIC_PB_URL=${_PUBLIC_PB_URL}"
      - "-t"
      - "${_IMAGE}"
      - "."
images:
  - "${_IMAGE}"
substitutions:
  _PUBLIC_PB_URL: ""
  _IMAGE: ""
